apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keda
spec:
  releaseName: keda
  chart:
    git: https://github.com/kedacore/charts
    path: keda
    ref: master
  values:
    replicaCount: 1
    image:
      keda: docker.io/kedacore/keda:1.4.1
      metricsAdapter: docker.io/kedacore/keda-metrics-adapter:1.4.1
      pullPolicy: Always
    operatorName: keda-operator
    rbac:
      create: true
    serviceAccount:
      create: true
      name: keda-operator
    logLevel: info
    logTimeFormat: epoch
    logLevelMetrics: 0
    service:
      type: ClusterIP
      portHttp: 80
      portHttpTarget: 8080
      portHttps: 443
      portHttpsTarget: 6443