apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-eventhub
  namespace: default
  labels:
    app: sample-eventhub
spec:
  selector:
    matchLabels:
      app: sample-eventhub
  template:
    metadata:
      labels:
        app: sample-eventhub
    spec:
      containers:
      - name: sample-eventhub
        image: mikkelhegn/sample-eventhub:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: EventHubTrigger
        envFrom:
        - secretRef:
            name: sample-eventhub
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: sample-eventhub
  namespace: default
  labels:
    deploymentName: sample-eventhub
spec:
  scaleTargetRef:
    deploymentName: sample-eventhub
  triggers:
  - type: azure-eventhub
    metadata:
      type: eventHubTrigger
      name: eventHubMessages
      direction: in
      eventHubName: samples-workitems
      connection: EventHub
      storageConnection: AzureWebJobsStorage
      cardinality: many
      consumerGroup: $Default
      dataType: string
---

